'use client';
import { subDays } from 'date-fns';

export type User = {
  id: string;
  username: string;
  password?: string;
  role: 'CREATOR' | 'ADMIN' | 'MANAGER';
  status: 'Active' | 'Inactive';
};

export type Customer = {
  id: string;
  name_en: string;
  name_ta: string;
  phone: string;
};

export type CustomerBalance = {
  customerId: string;
  balanceAmount: number;
  updatedAt?: any;
};

export type Uom = string;

export type Product = {
  id: string;
  name_en: string;
  name_ta: string;
  uom_allowed: Uom[];
};

export type BillItem = {
  id: string;
  billId?: string;
  product: string; // This is the Tamil name for display
  productId: string; // The actual product ID
  uom: string;
  qty: number;
  rate: number;
  amount: number;
  addedBy: string;
  stall: string;
};

export type LiveBillSummary = {
  billNo: string;
  customerName: string;
  customerId: string;
  amount: number;
  deliveryCharge?: number;
  paidAmount?: number;
  createdBy: string;
  stall: string;
  date?: any;
  finalBalance?: number;
  description?: string;
  prevBalance?: number;
}

export type Payment = {
    id: string;
    customerId: string;
    amount: number;
    date: any;
    notes?: string;
    isDeleted?: boolean;
    paymentMode?: "Cash" | "ACC" | "UPI" | "Bill Payment";
    linkedBillId?: string;  // Links auto-generated payment to its source bill
    autoGenerated?: boolean; // True for payments auto-created from bill save
}

export type Transaction = {
  date: Date;
  description: string;
  billedAmount?: number;
  receivedAmount?: number;
  balance: number;
  type: 'bill' | 'payment' | 'both';
  paymentId?: string; // Only set for type === 'payment' or 'both, links to Firestore doc
  paymentMode?: "Cash" | "ACC" | "UPI" | "Bill Payment";
  linkedBillId?: string;
};

export type SalesReportData = {
  customer: Customer;
  itemsByDate: { date: string; items: BillItem[] }[];
  totalQty: Record<string, number>;
  totalAmount: number;
  previousBalance: number;
  netAmount: number;
  dateRange: { from: Date; to: Date };
};

export type Vehicle = {
  id: string; // Registration Number
  name: string;
  active: boolean;
};

export type Driver = {
  id: string;
  name: string;
  licenseNumber: string;
  active: boolean;
};

export type Party = {
  id: string;
  name: string;
  location: string;
  active: boolean;
  createdAt?: any;
  updatedAt?: any;
};

export type PartyBalance = {
  partyId: string;
  balanceAmount: number;
  updatedAt?: any;
};

export type VehicleBill = {
  id: string;
  date: any; // Can be Date or Firestore Timestamp
  vehicleId: string; // Registration Number
  driverIds: string[];
  driverNames: string[];
  partyId: string;
  partyName: string;
  destination: string;
  advance: number;
  expenses: number;
  createdBy: string;
};

export type VehicleStatementTransaction = {
  date: Date;
  description: string;
  advance: number;
  expenses: number;
  balance: number;
};

export type PartyBillItem = {
  id: string; // A unique ID for the item row, e.g., timestamp
  productId: string;
  productName: string;
  rate: number;
  box: number;
  kgs: number;
  amount: number;
};

export type PartyBill = {
  id: string;
  date: any;
  partyId: string;
  partyName: string;
  totalBox: number;
  totalKgs: number;
  items: PartyBillItem[];
  totalAmount: number;
  commission: number;
  expenses: number;
  rent: number;
  totalDeductions: number;
  netAmount: number;
  cashReceived: number;
  bankReceived: number;
  totalReceived: number;
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};

export type StatementPrintHistory = {
  id: string;
  customerId: string;
  customerName: string;
  fromDate: any;
  toDate: any;
  statementAmount: number;
  printedAt: any;
  printedBy: string;
};

/**
 * BoxBill — represents a document in the `box_bills` Firestore collection.
 *
 * Firestore collection: box_bills
 *
 * Equivalent SQL schema:
 *   CREATE TABLE box_bills (
 *     id               TEXT PRIMARY KEY,   -- e.g. "BB1", "BB2"
 *     customer_id      UUID NOT NULL REFERENCES customers(id),
 *     bill_date        DATE NOT NULL,
 *     prev_balance_box INTEGER NOT NULL DEFAULT 0,
 *     todays_fish_box  INTEGER NOT NULL DEFAULT 0,
 *     total_box        INTEGER GENERATED ALWAYS AS (prev_balance_box + todays_fish_box),
 *     empty_box        INTEGER NOT NULL DEFAULT 0,
 *     balance_box      INTEGER GENERATED ALWAYS AS (total_box - empty_box),
 *     description      TEXT,
 *     driver_mobile    TEXT,
 *     driver_name      TEXT,
 *     vehicle_no       TEXT,
 *     created_by       TEXT NOT NULL,
 *     created_at       TIMESTAMP,
 *     updated_at       TIMESTAMP
 *   );
 */
export type BoxBill = {
  /** Document ID — e.g. "BB1", "BB2" */
  id: string;
  /** Foreign key → customers collection */
  customerId: string;
  /** Customer name snapshot for display */
  customerName: string;
  /** The billing date (Firestore Timestamp or ISO string) */
  billDate: any;
  /** Previous box balance carried forward */
  prevBalanceBox: number;
  /** Today's fish boxes received */
  todaysFishBox: number;
  /** prevBalanceBox + todaysFishBox (computed, stored for history) */
  totalBox: number;
  /** Empty boxes returned */
  emptyBox: number;
  /** totalBox - emptyBox (computed, stored for history) */
  balanceBox: number;
  /** Free-text note */
  description?: string;
  /** Driver mobile number */
  driverMobile?: string;
  /** Driver name */
  driverName?: string;
  /** Vehicle registration number */
  vehicleNo?: string;
  /** ID of the user who created the bill */
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};

/**
 * BoxBillEntry — represents individual box addition transactions throughout the day.
 * 
 * Firestore collection: box_bill_entries
 */
export type BoxBillEntry = {
  id: string;
  boxBillId: string;
  customerId: string;
  entryDate: any;
  boxesAdded: number;
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};
