'use client';
import { subDays } from 'date-fns';

export const roles = ['CREATOR', 'ADMIN', 'MANAGER', 'BOX'] as const;
export type Role = typeof roles[number];

export const pages = [
    'Dashboard',
    'Billing',
    'Vehicle Bill',
    'Party Bill',
    'Party Reports',
    'Party Statements',
    'Sales Report',
    'Bill History',
    'Payments',
    'Customer Balance',
    'Party Balance',
    'Customers',
    'Products',
    'Set Prices',
    'Manage Users',
    'Manage Vehicles',
    'Manage Drivers',
    'Manage Parties',
    'Permissions',
    'Profile',
    'Printer Settings',
    'UOM Settings',
    'Box Billing',
    'Party Box Billing',
    'Box Reports',
    'Party Box Reports',
    'Box Balance',
    'Party Box Balance',
    'Empty Box Entry',
] as const;
export type Page = typeof pages[number];

export const initialPermissions: Record<Role, Page[]> = {
  CREATOR: [...pages],
  ADMIN: [
    'Dashboard',
    'Billing',
    'Vehicle Bill',
    'Party Bill',
    'Party Reports',
    'Party Statements',
    'Sales Report',
    'Bill History',
    'Payments',
    'Customer Balance',
    'Party Balance',
    'Customers',
    'Products',
    'Set Prices',
    'Manage Vehicles',
    'Manage Drivers',
    'Manage Parties',
    'Profile',
    'Printer Settings',
    'UOM Settings',
    'Box Billing',
    'Party Box Billing',
    'Box Reports',
    'Party Box Reports',
    'Box Balance',
    'Party Box Balance',
    'Empty Box Entry',
  ],
  MANAGER: [
    'Dashboard',
    'Billing',
    'Vehicle Bill',
    'Party Bill',
    'Party Reports',
    'Party Statements',
    'Bill History',
    'Payments',
    'Profile',
    'Customer Balance',
    'Party Balance',
    'Sales Report',
    'Box Billing',
    'Box Balance',
    'Empty Box Entry',
    'Party Box Billing',
    'Party Box Balance',
  ],
  BOX: [
    'Profile',
    'Empty Box Entry',
  ],
};

export type User = {
  id: string;
  username: string;
  password?: string;
  role: 'CREATOR' | 'ADMIN' | 'MANAGER' | 'BOX';
  status: 'Active' | 'Inactive';
};

export type Customer = {
  id: string;
  name_en: string;
  name_ta: string;
  phone: string;
};

export type CustomerBalance = {
  customerId: string;
  balanceAmount: number;
  updatedAt?: any;
};

export type Uom = string;

export type Product = {
  id: string;
  name_en: string;
  name_ta: string;
  uom_allowed: Uom[];
};

export type BillItem = {
  id: string;
  billId?: string;
  product: string; // This is the Tamil name for display
  productId: string; // The actual product ID
  uom: string;
  qty: number;
  rate: number;
  amount: number;
  addedBy: string;
  stall: string;
};

export type LiveBillSummary = {
  billNo: string;
  customerName: string;
  customerId: string;
  amount: number;
  deliveryCharge?: number;
  paidAmount?: number;
  createdBy: string;
  stall: string;
  date?: any;
  finalBalance?: number;
  description?: string;
  prevBalance?: number;
  createdAt?: any;
}

export type Payment = {
    id: string;
    customerId: string;
    amount: number;
    date: any;
    notes?: string;
    isDeleted?: boolean;
    paymentMode?: "Cash" | "ACC" | "UPI" | "Bill Payment" | string;
    linkedBillId?: string;  // Links auto-generated payment to its source bill
    autoGenerated?: boolean; // True for payments auto-created from bill save
    createdAt?: any;
}

export type PartyPayment = {
  id: string;
  partyId: string;
  amount: number;
  date: any;
  notes?: string;
  isDeleted?: boolean;
  paymentMode?: "Cash" | "ACC" | "UPI" | "Bill Payment";
  linkedBillId?: string;
  autoGenerated?: boolean;
  createdAt?: any;
}

export type Transaction = {
  date: Date;
  description: string;
  billedAmount?: number;
  receivedAmount?: number;
  balance: number;
  type: 'bill' | 'payment' | 'both';
  paymentId?: string; // Only set for type === 'payment' or 'both, links to Firestore doc
  paymentMode?: "Cash" | "ACC" | "UPI" | "Bill Payment" | string;
  linkedBillId?: string;
};

export type SalesReportData = {
  customer: Customer;
  itemsByDate: { date: string; items: BillItem[] }[];
  totalQty: Record<string, number>;
  totalAmount: number;
  previousBalance: number;
  netAmount: number;
  dateRange: { from: Date; to: Date };
};

export type Vehicle = {
  id: string; // Registration Number
  name: string;
  active: boolean;
};

export type Driver = {
  id: string;
  name: string;
  licenseNumber: string;
  active: boolean;
};

export type Party = {
  id: string;
  name: string;
  location: string;
  active: boolean;
  createdAt?: any;
  updatedAt?: any;
};

export type PartyBalance = {
  partyId: string;
  balanceAmount: number;
  updatedAt?: any;
};

export type VehicleBill = {
  id: string;
  date: any; // Can be Date or Firestore Timestamp
  vehicleId: string; // Registration Number
  driverIds: string[];
  driverNames: string[];
  partyId: string;
  partyName: string;
  destination: string;
  advance: number;
  expenses: number;
  createdBy: string;
};

export type VehicleStatementTransaction = {
  date: Date;
  description: string;
  advance: number;
  expenses: number;
  balance: number;
};

export type PartyBillItem = {
  id: string; // A unique ID for the item row, e.g., timestamp
  productId: string;
  productName: string;
  rate: number;
  /** Generic quantity — mirrors BillItem.qty in Main Billing. Set on every
   *  item created or edited after the qty/UOM change. amount = qty * rate. */
  qty?: number;
  /** Unit for `qty` (KGS / BOX / TC ...). Sourced from Product.uom_allowed,
   *  exactly like Main Billing. Mirrors BillItem.uom. */
  uom?: string;
  /** LEGACY (bills saved before the qty/UOM change). `box` was the multiplier
   *  (amount = box * rate) and `kgs` was an informational kgs-per-box figure.
   *  Read-only for backward compatibility — never written by new/edited items. */
  box?: number;
  kgs?: number;
  amount: number;
};

/**
 * Quantity of a Party Bill item, for both the new (qty/uom) and the legacy
 * (box/kgs) shapes. In legacy bills `box` was the value multiplied by the rate,
 * so it is the quantity; no information is invented here.
 */
export const getPartyItemQty = (item: Pick<PartyBillItem, 'qty' | 'box'>): number =>
  item.qty ?? item.box ?? 0;

/** Unit of a Party Bill item. Legacy items were counted in boxes. */
export const getPartyItemUom = (item: Pick<PartyBillItem, 'uom'>): string =>
  item.uom ?? 'BOX';

/** True for items saved before the qty/UOM change (no qty and no uom stored). */
export const isLegacyPartyItem = (item: Pick<PartyBillItem, 'qty' | 'uom'>): boolean =>
  item.qty === undefined && item.uom === undefined;

/** One dated Cash or Bank payment recorded on a Party Bill. */
export type PartyBillPaymentEntry = {
  /** Firestore Timestamp when stored; any date-like value when read back. */
  date: any;
  amount: number;
};

type PartyBillPaymentSource = {
  date?: any;
  cashPayments?: PartyBillPaymentEntry[];
  bankPayments?: PartyBillPaymentEntry[];
  cashReceived?: number;
  bankReceived?: number;
  cashReceivedDate?: any;
  bankReceivedDate?: any;
};

/** True for bills saved with the multi-entry payment model. */
export const hasPartyBillPaymentEntries = (bill: Pick<PartyBillPaymentSource, 'cashPayments' | 'bankPayments'>): boolean =>
  Array.isArray(bill.cashPayments) || Array.isArray(bill.bankPayments);

/**
 * Cash entries of a Party Bill. New bills return their stored list as-is (in
 * the order entered). Legacy bills with a single cash figure are converted to
 * a one-entry list IN MEMORY — nothing is written back.
 */
export const getPartyBillCashEntries = (bill: PartyBillPaymentSource): PartyBillPaymentEntry[] => {
  if (Array.isArray(bill.cashPayments)) return bill.cashPayments;
  const amount = bill.cashReceived || 0;
  return amount !== 0 ? [{ date: bill.cashReceivedDate ?? bill.date, amount }] : [];
};

/** Bank / Acc entries of a Party Bill. Same rules as getPartyBillCashEntries. */
export const getPartyBillBankEntries = (bill: PartyBillPaymentSource): PartyBillPaymentEntry[] => {
  if (Array.isArray(bill.bankPayments)) return bill.bankPayments;
  const amount = bill.bankReceived || 0;
  return amount !== 0 ? [{ date: bill.bankReceivedDate ?? bill.date, amount }] : [];
};

/**
 * Net amount and total paid of a Party Bill, under the current model where
 * Advance is a payment. New bills already store both that way. Older bills
 * stored Advance (if any) as a deduction, so it is moved across in memory:
 * net goes up by it and paid goes up by it. Net minus paid — and so every
 * balance — is identical either way. For bills with no advance nothing
 * changes at all.
 */
export const getPartyBillAmounts = (
  bill: Pick<PartyBill, 'netAmount' | 'totalReceived' | 'cashReceived' | 'bankReceived' | 'advance' | 'cashPayments' | 'bankPayments'>
): { netAmount: number; totalPaid: number } => {
  const netAmount = bill.netAmount || 0;
  const received = bill.totalReceived !== undefined
    ? bill.totalReceived
    : (bill.cashReceived || 0) + (bill.bankReceived || 0);
  if (hasPartyBillPaymentEntries(bill)) return { netAmount, totalPaid: received };
  const legacyAdvance = bill.advance || 0;
  return { netAmount: netAmount + legacyAdvance, totalPaid: received + legacyAdvance };
};

export type PartyBill = {
  id: string;
  date: any;
  partyId: string;
  partyName: string;
  totalBox: number;
  totalKgs: number;
  items: PartyBillItem[];
  totalAmount: number;
  commission: number;
  expenses: number;
  /** Advance already paid by the party. A PAYMENT, not a deduction: it is part
   *  of totalReceived and never of totalDeductions. Optional — bills saved
   *  before this field existed read as 0. (Bills saved while Advance was briefly
   *  a deduction have no cashPayments/bankPayments arrays; see
   *  getPartyBillAmounts for how they are read.) */
  advance?: number;
  rent: number;
  totalDeductions: number;
  netAmount: number;
  /** SUM of cashPayments (kept in sync on every save so older readers work). */
  cashReceived: number;
  /** SUM of bankPayments (kept in sync on every save so older readers work). */
  bankReceived: number;
  /** Total paid on this bill = advance + cashReceived + bankReceived. This is
   *  the figure every balance calculation already uses. */
  totalReceived: number;
  /** Individual dated cash payments, in the order entered. Absent on bills
   *  saved before multiple entries existed — read those through
   *  getPartyBillCashEntries, which derives a one-entry list in memory. */
  cashPayments?: PartyBillPaymentEntry[];
  /** Individual dated bank / account payments. See cashPayments. */
  bankPayments?: PartyBillPaymentEntry[];
  /** Transaction date for the cash amount received. Independent of
   *  bankReceivedDate. Optional: bills saved before this field existed simply
   *  have no value, and are never back-filled. Informational only — it does not
   *  take part in any monetary calculation. */
  cashReceivedDate?: any;
  /** Transaction date for the bank/account amount received. See above. */
  bankReceivedDate?: any;
  // Since multiple entries: these two hold the FIRST entry's date, so
  // anything still reading the single-date fields sees a sensible value.
  previousBalance?: number;
  finalBalance?: number;
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};

export type StatementPrintHistory = {
  id: string;
  customerId: string;
  customerName: string;
  fromDate: any;
  toDate: any;
  statementAmount: number;
  printedAt: any;
  printedBy: string;
};

/**
 * BoxBill — represents a document in the `box_bills` Firestore collection.
 *
 * Firestore collection: box_bills
 *
 * Equivalent SQL schema:
 *   CREATE TABLE box_bills (
 *     id               TEXT PRIMARY KEY,   -- e.g. "BB1", "BB2"
 *     customer_id      UUID NOT NULL REFERENCES customers(id),
 *     bill_date        DATE NOT NULL,
 *     prev_balance_box INTEGER NOT NULL DEFAULT 0,
 *     todays_fish_box  INTEGER NOT NULL DEFAULT 0,
 *     total_box        INTEGER GENERATED ALWAYS AS (prev_balance_box + todays_fish_box),
 *     empty_box        INTEGER NOT NULL DEFAULT 0,
 *     balance_box      INTEGER GENERATED ALWAYS AS (total_box - empty_box),
 *     description      TEXT,
 *     driver_mobile    TEXT,
 *     driver_name      TEXT,
 *     vehicle_no       TEXT,
 *     created_by       TEXT NOT NULL,
 *     created_at       TIMESTAMP,
 *     updated_at       TIMESTAMP
 *   );
 */
export type BoxBill = {
  /** Document ID — e.g. "BB1", "BB2" */
  id: string;
  /** Foreign key → customers collection */
  customerId: string;
  /** Customer name snapshot for display */
  customerName: string;
  /** The billing date (Firestore Timestamp or ISO string) */
  billDate: any;
  /** Previous box balance carried forward */
  prevBalanceBox: number;
  /** Today's fish boxes received */
  todaysFishBox: number;
  /** prevBalanceBox + todaysFishBox (computed, stored for history) */
  totalBox: number;
  /** Empty boxes returned */
  emptyBox: number;
  /** User typed in bill */
  manualEmptyBox?: number;
  /** From Empty Box Entry page */
  entryEmptyBoxTotal?: number;
  /** Sum of both */
  finalEmptyBox?: number;
  /** totalBox - emptyBox (computed, stored for history) */
  balanceBox: number;
  /** Free-text note */
  description?: string;
  /** Driver mobile number */
  driverMobile?: string;
  /** Driver name */
  driverName?: string;
  /** Vehicle registration number */
  vehicleNo?: string;
  /** ID of the user who created the bill */
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};

/**
 * BoxBillEntry — represents individual box addition transactions throughout the day.
 * 
 * Firestore collection: box_bill_entries
 */
export type BoxBillEntry = {
  id: string;
  boxBillId: string;
  customerId: string;
  entryDate: any;
  boxesAdded: number;
  emptyBoxesAdded?: number;
  /** True when this entry was auto-created from the manual Empty Box input on save.
   *  Used to avoid double-counting with the manualEmptyBox state during live recalculation. */
  isManualEmpty?: boolean;
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};


export type PartyBoxBill = {
  id: string;
  partyId: string;
  partyName: string;
  billDate: any;
  prevBalanceBox: number;
  todaysFishBox: number;
  totalBox: number;
  emptyBox: number;
  manualEmptyBox?: number;
  entryEmptyBoxTotal?: number;
  finalEmptyBox?: number;
  balanceBox: number;
  description?: string;
  driverMobile?: string;
  driverName?: string;
  vehicleNo?: string;
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};

/**
 * PartyBoxBillEntry — individual box additions for a PartyBoxBill.
 * Firestore collection: party_box_bill_entries
 */
export type PartyBoxBillEntry = {
  id: string;
  partyBoxBillId: string;
  partyId: string;
  entryDate: any;
  boxesAdded: number;
  emptyBoxesAdded?: number;
  isManualEmpty?: boolean;
  createdBy: string;
  createdAt?: any;
  updatedAt?: any;
};
